Fetch secrets from Vault
SonarSource/sslr pull request #37
Opened 2022-11-07 12:28 UTC by elrzn

2022-11-07 16:19 UTC, elrzn commented
Error seems to be dev related.

2022-11-08 10:18 UTC, elrzn commented
Hi @SonarSource/languages-team-cfamily can you maybe take a look? I believe the build error is not caused by the PR changes.

https://cirrus-ci.com/task/5534953210380288

2022-11-16 00:51 UTC, Godin requested changes
`.github/workflows/release.yml` should also be updated.

2022-11-17 07:57 UTC, elrzn commented on .github/workflows/release.yml
> +      mavenCentralSync: true
Note: No Slack notifications as I don't know which channel to use.

2022-11-17 21:43 UTC, Godin requested changes

2022-11-17 21:43 UTC, Godin commented on .cirrus.yml
> +  ARTIFACTORY_PRIVATE_PASSWORD: VAULT[development/artifactory/token/SonarSource-sslr-private-reader access_token]
```suggestion
  ARTIFACTORY_PRIVATE_PASSWORD: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-private-reader access_token]
```

2022-11-17 21:43 UTC, Godin commented on .cirrus.yml
> +  ARTIFACTORY_DEPLOY_PASSWORD: VAULT[development/artifactory/token/SonarSource-sslr-qa-deployer access_token]
```suggestion
  ARTIFACTORY_DEPLOY_PASSWORD: VAULT[development/artifactory/token/SonarSource-sonar-lits-qa-deployer access_token]
```

2022-11-17 21:43 UTC, Godin commented on .cirrus.yml
> +    GITHUB_TOKEN: VAULT[development/github/token/SonarSource-sslr-promotion token]
```suggestion
    GITHUB_TOKEN: VAULT[development/github/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-promotion token]
```

2022-11-18 14:04 UTC, Godin approved these changes

2022-11-18 14:04 UTC, merged